### ISSUE TITLE
Regular meeting?

### ISSUE THREAD

**Issue by jbenet** [ipfs/research-bitswap#3]
Should we organize a regular meeting for those of us interested in this?

- @dgrisham is interested in doing work around Bitswap, measurements, deploying new agents, etc.
- @whyrusleeping @diasdavid and @jbenet have been meaning to do this for ages.
- @nicola is probably very interested too
- new work on the test-lab will make this much more possible
- js-ipfs working could help us deploy tests through the browser to 10,000s of people
- new work on Filecoin will make it much more relevant (TBA in coming months)
- Unfort. this is low priority for me until May/June, so i dont think i can swing more than 20min weekly, or 40min bi-weekly.

cc @dgrisham @whyrusleeping @nicola

**Comment by daviddias** [comment]
//cc @pgte who might be interested in partaking in this research too :)

**Comment by dgrisham** [comment]
Hey everyone --

I'm specifically interested in this resource for my master's thesis, so I'm definitely going to be working on it. I think a call could be a great way for me to get some of your thoughts and bounce my own off of you. I know many of you may be busy, so it could be as simple as a 20 min call a week if that's all you want to commit.

In the case that you're interested in doing a bit more with this (or just want more details), my current game plan is to get a good simulation test bed together for investigating Bitswap strategies. I don't have hard details on this right now, but a good place to start would be the [first issue Juan posted](https://github.com/ipfs/bitswap-research/issues/1). At a higher level, the loose goals involve determining how certain strategies perform and whether they're resistant to certain types of attacks, as well as the general feasibility of sybil attacks/freeriders/etc.

Let me know if there are questions over any of that, or interest in being involved in this!

**Comment by nicola** [comment]
Happy to join, unfortunately will be busy until May :(

**Comment by dgrisham** [comment]
For everyone still interested in this, I'd love to get your feedback on this: https://github.com/ipfs/go-ipfs/pull/3982 (be sure to read my comment at the end of the page titled 'Update: Alternative Implementation Idea', which is a bit different from what's presented in the OP). @jbenet @nicola @diasdavid

**Comment by dgrisham** [comment]
Hey all -- is there interest in a regular meeting at this point? Know @jbenet will be too busy until at least mid-July, but I'd be happy to catch anyone up on what's happened/the current plan. The current state of this is something like:

**Theory**: Model reciprocative Bitswap strategies using evolutionary game theory (EGT). See [the 'P2P Soft Security' paper here](https://github.com/ipfs/bitswap-research/issues/2#issuecomment-287792540) for the inspiration for this idea. There's still reading to do (of other papers using EGT for similar purposes) along with work to come up with our own EGT model that best matches what we have in Bitswap (balanced against computational feasibility).

**Implementation**: Test various strategies using the IPTL and find best way(s) to connect to the EGT model. This involves [implementing strategies into Bitswap](https://github.com/ipfs/go-ipfs/pull/3982) as well as adding features to https://github.com/ipfs/kubernetes-ipfs/ that will act as a simulation test bed.

 cc @whyrusleeping @nicola @diasdavid @pgte

**Comment by flyingzumwalt** [comment]
cc @lgierth, who loves bitswap

**Comment by daviddias** [comment]
cc @mafintosh who has showed interested multiple times in Bitswap :)

**Comment by dgrisham** [comment]
@jbenet: @miyazono and I are going to meet on a call tomorrow to discuss the applicability of the mathematical methods in the *Game Theory and Topological Phase Transition* paper (second link here https://github.com/ipfs/research-bitswap/issues/2#issuecomment-324150508), will you be available to join? We're planning on doing it at 21:00 UTC (same time you and I had our schedule meeting in the past).

Everyone else is welcome as well :) Don't feel like you have to read/understand that entire paper, I'm only around section 4 myself. We just want to start a discussion as to whether the methods make sense for a Bitswap model. Feel free to just come and listen in!

**Comment by nicola** [comment]
hey @dgrisham add it to ipfs/pm maybe? other people might be interested to join! :)

**Comment by dgrisham** [comment]
@nicola Good thinking, will do :)

**Comment by daviddias** [comment]
@dgrisham @miyazono managed to update the community calendar and added the research-bitswap call

See it here https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com&ctz=America/New_York

Also created a recurring zoom url -- https://protocol.zoom.us/j/959863667 -- that you can find on the calendar invite

**Comment by miyazono** [comment]
We're now moving this to a Friday call.  We're working on an update to the calendar.

**Comment by daviddias** [comment]
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/1211152/35308426-8efd19fa-005c-11e8-984c-2d24c530d131.png">

https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com&ctz=America/New_York
